/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AppMain;


import Ejb.Users;
import gui.DepartamentiForm;
import gui.FormatForm;
import gui.GrupiKlienteveForm;
import gui.GrupiProdukteveForm;
import gui.KlientiForm;
import gui.KontrataForm;
import gui.MarketingForm;
import gui.OfertaForm;
import gui.OpenLeadForm;
import gui.OpportunitiesForm;
import gui.ProduktiForm;
import gui.PunetoriForm;
import gui.QmimorjaForm;
import gui.RoleForm;
import gui.UsersForm;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Drilon
 */
public class Menu extends javax.swing.JFrame {

    Integer role;
    Users r;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIcon();
       
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JMenuBar();
        KlientiMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        PunetoriMenu = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        mPunetoriForm = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mUsersForm = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        ProduktiMenu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(6, 135, 202));

        MenuBar.setBackground(new java.awt.Color(153, 204, 255));
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBar.setPreferredSize(new java.awt.Dimension(216, 28));

        KlientiMenu.setText(" Klienti    ");

        jMenuItem1.setText("Klienti");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(77, 27));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        KlientiMenu.add(jMenuItem1);

        jMenuItem2.setText("GrupiKlienteve");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(121, 27));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        KlientiMenu.add(jMenuItem2);

        MenuBar.add(KlientiMenu);

        PunetoriMenu.setText("Punëtori    ");

        jMenuItem12.setText("Departamenti");
        jMenuItem12.setPreferredSize(new java.awt.Dimension(115, 27));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        PunetoriMenu.add(jMenuItem12);

        mPunetoriForm.setText("Punëtori");
        mPunetoriForm.setPreferredSize(new java.awt.Dimension(115, 27));
        mPunetoriForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPunetoriFormActionPerformed(evt);
            }
        });
        PunetoriMenu.add(mPunetoriForm);

        jMenuItem11.setText("Kontrata");
        jMenuItem11.setPreferredSize(new java.awt.Dimension(115, 27));
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        PunetoriMenu.add(jMenuItem11);

        mUsersForm.setText("Shfrytëzuesit");
        mUsersForm.setPreferredSize(new java.awt.Dimension(115, 27));
        mUsersForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsersFormActionPerformed(evt);
            }
        });
        PunetoriMenu.add(mUsersForm);

        jMenuItem10.setText("Rolet");
        jMenuItem10.setPreferredSize(new java.awt.Dimension(115, 27));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        PunetoriMenu.add(jMenuItem10);

        jMenuItem13.setText("Format");
        jMenuItem13.setPreferredSize(new java.awt.Dimension(81, 27));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        PunetoriMenu.add(jMenuItem13);

        MenuBar.add(PunetoriMenu);

        ProduktiMenu.setText("Produkti      ");

        jMenuItem5.setText("Produkti");
        jMenuItem5.setPreferredSize(new java.awt.Dimension(141, 27));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        ProduktiMenu.add(jMenuItem5);

        jMenuItem4.setText("Grupi i Produkteve");
        jMenuItem4.setPreferredSize(new java.awt.Dimension(141, 27));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        ProduktiMenu.add(jMenuItem4);

        jMenuItem3.setText("Qmimorja");
        jMenuItem3.setPreferredSize(new java.awt.Dimension(141, 27));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        ProduktiMenu.add(jMenuItem3);

        MenuBar.add(ProduktiMenu);

        jMenu1.setText("Marketingu");
        jMenu1.setPreferredSize(new java.awt.Dimension(69, 17));

        jMenuItem6.setText("Marketing");
        jMenuItem6.setPreferredSize(new java.awt.Dimension(117, 27));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Oferta");
        jMenuItem7.setPreferredSize(new java.awt.Dimension(117, 27));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Open Lead");
        jMenuItem8.setPreferredSize(new java.awt.Dimension(117, 27));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Opportunities");
        jMenuItem9.setPreferredSize(new java.awt.Dimension(117, 27));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mUsersFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsersFormActionPerformed
        // TODO add your handling code here:
        UsersForm ap=new UsersForm();
        DesktopPane.add(ap);
        ap.show();
       
    }//GEN-LAST:event_mUsersFormActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      KlientiForm k=new KlientiForm();
      DesktopPane.add(k);
      k.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        GrupiKlienteveForm gk=new GrupiKlienteveForm();
        DesktopPane.add(gk);
        gk.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        QmimorjaForm q=new QmimorjaForm();
        DesktopPane.add(q);
        q.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        GrupiProdukteveForm gp=new GrupiProdukteveForm();
        DesktopPane.add(gp);
        gp.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ProduktiForm pf=new ProduktiForm();
        DesktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mPunetoriFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPunetoriFormActionPerformed
        // TODO add your handling code here:
        PunetoriForm ap=new PunetoriForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_mPunetoriFormActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        MarketingForm ap=new MarketingForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        OfertaForm ap=new OfertaForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        OpenLeadForm ap=new OpenLeadForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        OpportunitiesForm ap=new OpportunitiesForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        RoleForm ap=new RoleForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        KontrataForm ap=new KontrataForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        DepartamentiForm ap=new DepartamentiForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FormatForm ap=new FormatForm();
        DesktopPane.add(ap);
        ap.show();
    }//GEN-LAST:event_jMenuItem13ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu KlientiMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu ProduktiMenu;
    public javax.swing.JMenu PunetoriMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mPunetoriForm;
    private javax.swing.JMenuItem mUsersForm;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.jpg")));
    }
}
